services:
    CleverAge\EAVApiPlatformBundle\Metadata\Property\Factory\EAVPropertyNameCollectionFactory:
        decorates: api_platform.metadata.property.name_collection_factory
        arguments:
            - '@CleverAge\EAVApiPlatformBundle\Metadata\Property\Factory\EAVPropertyNameCollectionFactory.inner'
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '%sidus_eav_model.normalizer.data.ignored_attributes%'

    CleverAge\EAVApiPlatformBundle\Metadata\Property\Factory\FamilyPropertyMetadataFactory:
        decorates: api_platform.metadata.property.metadata_factory
        arguments:
            - '@CleverAge\EAVApiPlatformBundle\Metadata\Property\Factory\FamilyPropertyMetadataFactory.inner'
