services:
    CleverAge\EAVApiPlatformBundle\Metadata\Property\Factory\EAVPropertyNameCollectionFactory:
        decorates: api_platform.metadata.property.name_collection_factory
        arguments:
            - '@CleverAge\EAVApiPlatformBundle\Metadata\Property\Factory\EAVPropertyNameCollectionFactory.inner'
            - '@CleverAge\EAVApiPlatformBundle\Resolver\FamilyResolver'
            - '%sidus_eav_model.normalizer.data.ignored_attributes%'

    CleverAge\EAVApiPlatformBundle\Metadata\Property\Factory\FamilyPropertyMetadataFactory:
        decorates: api_platform.metadata.property.metadata_factory
        arguments:
            - '@CleverAge\EAVApiPlatformBundle\Metadata\Property\Factory\FamilyPropertyMetadataFactory.inner'

    CleverAge\EAVApiPlatformBundle\Metadata\Property\Factory\EAVAttributeMetadataFactory:
        decorates: api_platform.metadata.property.metadata_factory
        arguments:
            - '@CleverAge\EAVApiPlatformBundle\Metadata\Property\Factory\EAVAttributeMetadataFactory.inner'
            - '@property_info'
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@api_platform.resource_class_resolver'
